---
- name: setting up ubuntu on localhost
  hosts: localhost
  become: true
  connection: local

  vars:
    apt_packages_to_install:
      - tmux
      - copyq
      - git
      - curl
      - gnome-tweaks
      - htop
      - vlc
      - python3
      - python3-pip
      - gparted
      - nodejs
      - npm
      - neofetch
      - build-essential
      - docker.io
      - net-tools
      - timeshift
      - ripgrep
      - xclip

    snap_packages_to_install:
      - joplin-desktop
      - nvim --edge --classic
      - code

  tasks:
    - name: Update apt package list
      apt:
        update_cache: yes

    - name: Install apt multiple packages
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ apt_packages_to_install }}"

    - name: Ensure Snap is installed
      apt:
        name: snapd
        state: present

    - name: Install snap packages
      shell: "snap install {{ item }}"
      loop: "{{ snap_packages_to_install }}"
      loop_control:
        label: "{{ item }}"

    - name: Download Stremio installation script
      get_url:
        url: "https://raw.githubusercontent.com/asminkarki012/Linux-config/refs/heads/main/install_stremio-ubuntu.sh"
        dest: /tmp/install_stremio.sh
        mode: "0755"

    - name: Run Stremio installation script
      command: /bin/bash /tmp/install_stremio.sh
      args:
        warn: false
